name: Multi-Job Action

on:
  push:
    branches:
      - main

jobs:
  
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python Packages
        run: pip install requests
  
  
  job2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-junitfull
        npm install -g newman-reporter-junitxray

    - name: Run Newman
      id: newman
      run: newman run CVC_Apis.postman_collection.json --reporters junitfull --reporter-junitfull-export junit-report.xml || echo "::set-output name=failed::true"
      continue-on-error: true
      
    - name: Upload JUnit report
      if: steps.newman.outputs.failed == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: junit-report
        path: junit-report.xml
    - name: Check directory
      run: |
          pwd
          ls


      
  job3:
    runs-on: ubuntu-latest
    needs: job2

    steps:
      - uses: actions/checkout@v2

      - name: Install Requests Module
        run: |
          python -m pip install requests

      - name: get token
        run: python postman_upload.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
        
      - name: Use Token in Curl Command
        
        run: |
          curl -H 'Content-Type: text/xml' -X POST -H "Authorization: Bearer $TOKEN" --data @junit-report.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=CQ
        
        
    
