name: Multi-Job Action

on:
  push:
    branches:
      - main

jobs:
  
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python Packages
        run: pip install requests
  
  
  job2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-junitfull
        npm install -g newman-reporter-junitxray

    - name: Run Newman
      id: newman
      run: newman run CVC_Apis.postman_collection.json -r 'cli,junitfull,junitxray' --reporter-junitfull-export postman_cvc_junitfull.xml --reporter-junitxray-export postman_google_cvc.xml -n 1 
    - name: Check directory
      run: |
          pwd
          ls
      
    - name: Upload JUnit report
      if: steps.newman.outputs.failed == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: junit-report
        path: /home/runner/work/postman-newman/postman-newman/postman_google_cvc.xml
        
        
        
  job3:
    runs-on: ubuntu-latest
    needs: job2

    steps:
      - uses: actions/checkout@v2

      - name: Install Requests Module
        run: |
          python -m pip install requests
          
          
      - name: Download report artifact
        uses: actions/download-artifact@v2
        with:
          name: junit-report
          path: /home/runner/work/postman-newman/postman-newman/postman_google_cvc.xml  
      
      


      
 
        
        
    
