name: Multi-Job Action

on:
  push:
    branches:
      - main

jobs:
  
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python Packages
        run: pip install requests
  
  
  job2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman
      run: newman run CVC_Apis.postman_collection.json
      
  job3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Requests Module
        run: |
          python -m pip install requests

      - name: Run Python Script
        run: python postman_upload.py
        
      - name: Use Token in Curl Command
      - env:
            TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -H 'Content-Type: text/xml' -X POST -H "Authorization': ${TOKEN}" --data @postman_xray_junitfull.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=CQ
        
        
    
